### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by A-312** [A-312/node-blueconfig#21]
- [ ] [Improve doc about custom `env` getter](https://github.com/mozilla/node-convict/issues/224#issuecomment-571358828) / [And this one](https://github.com/mozilla/node-convict/issues/128#issuecomment-571355830) / I think I will improve default `env` getter function with an option.
 - [ ] [Follow JSON Schema standard for enum value, and *change behavior of array format ?*](https://github.com/mozilla/node-convict/issues/7) / [this one too](https://github.com/mozilla/node-convict/issues/322)
 - [ ] [Improve doc about custom `arg` getter](https://github.com/mozilla/node-convict/issues/125#issuecomment-571349692)
 - [ ] [Add a build function ?](https://github.com/mozilla/node-convict/issues/237) / [here there is one too](https://github.com/mozilla/node-convict/issues/291)
 - [ ] [Custom coerce](https://github.com/mozilla/node-convict/issues/285)
